CREATE DATABASE IF NOT EXISTS ibge;

CREATE TABLE IF NOT EXISTS pessoas ( 
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR (100) NOT NULL,
    data_nascimento DATE NOT NULL,
    cpf VARCHAR (11) NOT NULL,
    rg VARCHAR (9) NOT NULL

);

CREATE TABLE IF NOT EXISTS religioes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR (100) NOT NULL
);

CREATE TABLE IF NOT EXISTS sexualidades (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR (100) NOT NULL
);

CREATE TABLE IF NOT EXISTS profissoes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR (100) NOT NULL
);

CREATE TABLE IF NOT EXISTS etnias (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR (100) NOT NULL
);

CREATE TABLE IF NOT EXISTS cidades (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR (100) NOT NULL,
    estados VARCHAR (2) NOT NULL,
    pais VARCHAR (100) NOT NULL,
    cep VARCHAR (8) NOT NULL
);

CREATE TABLE IF NOT EXISTS generos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR (100) NOT NULL
);